export const courseData: any[] = [
  {
    img: '../../../../assets/programe/react.jpg',
    title: 'Master React js / 12 semaines',
    author: 'Mr Djigo',
    ratingValue: 4.6,
    rating: 'bi bi-star-fill text-warning',
    level: 'Débutant',
    value: 3.045,
    time: 5,
  },
  {
    img: '../../../../assets/programe/py.png',
    title: 'Master React js / 12 semaines',
    author: 'Mr Biteye',
    ratingValue: 4.5,
    rating: 'bi bi-star-fill',
    level: 'Intermedaire',
    value: 5.045,
    time: 4,
  },
  {
    img: '../../../../assets/programe/ui&ux.avif',
    title: 'Introduction to Python / 4 semaines',
    author: 'Mrs Ngom',
    ratingValue: 4.5,
    rating: 'bi bi-star-fill',
    level: 'Advance',
    value: 5.045,
  },
  {
    img: './../../../assets/programe/node.jpeg',
    title: 'Explore node js / 6 Month',
    author: 'Mr Niass',
    ratingValue: 4.6,
    rating: 'bi bi-star-fill',
    level: 'Advance',
    value: 4.645,
  },
  {
    img: '../../../../assets/programe/webdev.jpg',
    title: 'Web developement / 3 semaines',
    author: 'Mrs Mbodj',
    ratingValue: 4.8,
    rating: 'bi bi-star-fill',
    level: 'débutant',
    value: 4.845,
  },
  {
    img: '../../../../assets/programe/ja.jpg',
    title: 'Introduction to Java / 4 Month',
    author: 'Mr Seck',
    ratingValue: 4.3,
    rating: 'bi bi-star-fill',
    level: 'Intermédaire',
    value: 4.345,
  },
  {
    img: '../../../../assets/programe/javascript.jpeg',
    title: 'Maitrise Vanilla javascript / 2 mois',
    author: 'Mr Hattaby',
    ratingValue: 5.5,
    rating: 'bi bi-star-fill',
    level: 'Débutant',
    value: 5.545,
  },
  {
    img: './../../../assets/programe/api.png',
    title: 'Travail avec les API',
    author: 'Mr Nassir',
    ratingValue: 4.7,
    rating: 'bi bi-star-fill',
    level: 'Advance',
    value: 4.745,
  },
  {
    img: '../../../../assets/programe/cloud.jpeg',
    title: 'learn cloud computing higth demande skill',
    author: 'Mr Mar',
    ratingValue: 4.5,
    rating: 'bi bi-star-fill',
    level: 'Interm"daire',
    value: 4.545,
  },
];
